apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hasher-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasher-label
  template:
    metadata:
      labels:
        app: hasher-label
    spec:
      containers:
        -
          image: mjgrppr/mj-dockercoins:latest-hasher
          name: hasher-container
          ports:
            - containerPort: 8080
