apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webui-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webui-label
  template:
    metadata:
      labels:
        app: webui-label
    spec:
      containers:
        -
          image: mjgrppr/mj-dockercoins:latest-webui
          name: webui-container
          ports:
            - containerPort: 8080
